/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public boolean isPrime(long n) {
        double m = Math.sqrt(n)+1;
        if(n==2)
            return true;
        if(n%2==0)
            return true;
        for (long i =3;i<m;i+=2){
            if (n%i==0)
                return false;
        }
        return true;
    }

    public static void main(String[] args) {
       if(args.length<1||args.length>1){
           System.out.println("Input a number");
           System.exit(0);
       }
       App app = new App();
       long in = Long.parseLong(args[0]);
        System.out.println(app.isPrime(in));
    }
}
