/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void testSmallPrime() {
        App app = new App();
        assertEquals(app.isPrime(17),true);
    }
    @Test
    public void testSmallNoPrime() {
        App app = new App();
        assertEquals(app.isPrime(33),false);
    }
    @Test
    public void testLargePrime() {
        App app = new App();
        assertEquals(app.isPrime(32416189049L),true);
    }
    @Test
    public void testLargeNoPrime() {
        App app = new App();
        assertEquals(app.isPrime(32416169051L),false);
    }
}
